//List of files which are indexed.
fl = new Array();
fl["0"]= "accesshokiespa.html";
fl["1"]= "addressesandnumbers.html";
fl["2"]= "administrativeholds.html";
fl["3"]= "authorizepayers.html";
fl["4"]= "confidentiality.html";
fl["5"]= "courserequest.html";
fl["6"]= "dars.html";
fl["7"]= "diningplans.html";
fl["8"]= "dropadd.html";
fl["9"]= "ebill.html";
fl["10"]= "emergencycontacts.html";
fl["11"]= "finalgrades.html";
fl["12"]= "gradesmenu.html";
fl["13"]= "hokiespa.html";
fl["14"]= "housinganddiningservices.html";
fl["15"]= "housingcontract.html";
fl["16"]= "overallgpa.html";
fl["17"]= "personalinformation.html";
fl["18"]= "registrationandschedule.html";
fl["19"]= "roomassignments.html";
fl["20"]= "semestergpa.html";
fl["21"]= "timetable.html";
fl["22"]= "transfercredit.html";
fl["23"]= "universityaccountinfo.html";
var doStem = false